name: 'AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions'
description: "Deploys a AWS CloudFormation stack"
branding:
  icon: "cloud"
  color: "orange"
inputs:
  mode:
    description: "Operation mode: 'create-and-execute' (default), 'create-only', or 'execute-only'"
    required: false
    default: "create-and-execute"
  name:
    description: "The name of the CloudFormation stack"
    required: true
  template:
    description: "The path or URL to the CloudFormation template"
    required: false
  capabilities:
    description: "The comma-delimited list of stack template capabilities to acknowledge. Defaults to 'CAPABILITY_IAM'"
    required: false
    default: "CAPABILITY_IAM"
  parameter-overrides:
    description: 'The parameters to override in the stack inputs. You can pass a comma-delimited list or a file URL. Comma-delimited list has each entry formatted as <ParameterName>=<ParameterValue> or <ParameterName>="<ParameterValue>,<ParameterValue>". A JSON file can be a local file with a "file://" prefix or remote URL. The file should look like: [ { "ParameterKey": "KeyPairName", "ParameterValue": "MyKey" }]'
    required: false
  no-execute-changeset:
    description: "Indicates whether to execute to the change set or have it reviewed (default: false)"
    required: false
    default: false
  no-delete-failed-changeset:
    description: "Indicates whether to delete to a failed change set (default: false)"
    required: false
    default: false
  fail-on-empty-changeset:
    description: "If the CloudFormation change set is empty, fail the action (default: false)"
    required: false
    default: false
  disable-rollback:
    description: "Disable rollback of the stack if stack creation fails (default: false). This input is only used for stack creation, not for stack update"
    required: false
    default: false
  timeout-in-minutes:
    description: "The amount of time that can pass before the stack status becomes CREATE_FAILED. This input is only used for stack creation, not for stack update"
    required: false
  notification-arns:
    description: "The comma-delimited list of Amazon SNS topic ARNs to publish stack related events"
    required: false
  role-arn:
    description: "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that AWS CloudFormation assumes to create the stack. AWS CloudFormation uses the role's credentials to make calls on your behalf. AWS CloudFormation always uses this role for all future operations on the stack. As long as users have permission to operate on the stack, AWS CloudFormation uses this role even if the users don't have permission to pass it. Ensure that the role grants least privilege. If you don't specify a value, AWS CloudFormation uses the role that was previously associated with the stack"
    required: false
  tags:
    description: 'Key-value pairs to associate with this stack. This input should be JSON-formatted, for example [ { "Key": "string", "Value": "string" } ]'
    required: false
  termination-protection:
    description: "Whether to enable termination protection on the specified stack (default: false). This input is only used for stack creation, not for stack update"
    required: false
    default: false
  http-proxy:
    description: 'Proxy to use for the AWS SDK agent'
    required: false
  change-set-name:
    description: "The name of the change set to create. Defaults to '<stack-name>-CS'"
    required: false
  include-nested-stacks-change-set:
    description: "Creates a change set for the all nested stacks specified in the template. Defaults to '0' (will not include nested stacks)"
    required: false
    default: "0"
  execute-change-set-id:
    description: "Execute an existing change set by ID or name instead of creating a new one. When provided, only 'name' (stack name) is required."
    required: false
  deployment-mode:
    description: "The deployment mode for the change set. Use 'REVERT_DRIFT' to create a change set that reverts drift. Defaults to standard deployment."
    required: false
outputs:
  stack-id:
    description: "The id of the deployed stack. In addition, any outputs declared in the deployed CloudFormation stack will also be set as outputs for the action, e.g. if the stack has a stack output named 'foo', this action will also have an output named 'foo'."
  change-set-id:
    description: "The id of the created change set (only when no-execute-changeset is true)"
  change-set-name:
    description: "The name of the created change set (only when no-execute-changeset is true)"
  has-changes:
    description: "Whether the change set contains any changes (only when no-execute-changeset is true)"
  changes-count:
    description: "Number of changes in the change set (only when no-execute-changeset is true)"
  changes-summary:
    description: "JSON summary of changes in the change set (only when no-execute-changeset is true)"
  changes-markdown:
    description: "Markdown-formatted change set summary for PR comments (only when no-execute-changeset is true)"
runs:
  using: "node20"
  main: "dist/index.js"
